name = "uiuc-course-search"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
CURRENT_YEAR = "2025"
CURRENT_TERM = "fall"
CISAPI_BASE = "https://courses.illinois.edu/cisapp/explorer"

[[d1_databases]]
binding = "DB"
database_name = "course-search-db"
database_id = "ae2bcf8a-c988-4e93-81a7-0c96c089e5d6"

[[vectorize]]
binding = "VECTORIZE"
index_name = "course-embeddings"

[ai]
binding = "AI"
