import {
  alpha,
  createTheme,
  rem,
  type CSSVariablesResolver,
  type MantineColorsTuple,
  type MantineThemeOverride,
} from '@mantine/core'

const stoneColors: MantineColorsTuple = ['#fafaf9', '#f5f5f4', '#e7e5e4', '#d6d3d1', '#a8a29e', '#57534e', '#44403c', '#292524', '#1c1917', '#0c0a09', '#78716C']
const orangeColors: MantineColorsTuple = ['#fff7ed', '#ffedd5', '#fed7aa', '#fdba74', '#fb923c', '#f97316', '#ea580c', '#9a3412', '#7c2d12', '#431407', '#F97316']

export const shadcnTheme: MantineThemeOverride = createTheme({
  colors: {
    stone: stoneColors,
    orange: orangeColors,
    primary: orangeColors,
    secondary: stoneColors,
    dark: stoneColors,
  },
  focusRing: 'never',
  scale: 1,
  primaryColor: 'primary',
  primaryShade: { light: 5, dark: 6 },
  autoContrast: false,
  luminanceThreshold: 0.3,
  fontFamily: 'Geist, Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  headings: {
    fontFamily: 'Geist, Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    sizes: {
      h1: { fontSize: rem('36px'), lineHeight: rem('44px'), fontWeight: '600' },
      h2: { fontSize: rem('30px'), lineHeight: rem('38px'), fontWeight: '600' },
      h3: { fontSize: rem('24px'), lineHeight: rem('32px'), fontWeight: '600' },
      h4: { fontSize: rem('20px'), lineHeight: rem('30px'), fontWeight: '600' },
    },
  },
  radius: {
    xs: rem('6px'),
    sm: rem('8px'),
    md: rem('12px'),
    lg: rem('16px'),
    xl: rem('24px'),
  },
  defaultRadius: 'sm',
  spacing: {
    '4xs': rem('2px'),
    '3xs': rem('4px'),
    '2xs': rem('8px'),
    xs: rem('10px'),
    sm: rem('12px'),
    md: rem('16px'),
    lg: rem('20px'),
    xl: rem('24px'),
    '2xl': rem('28px'),
    '3xl': rem('32px'),
    '4xl': rem('40px'),
  },
  fontSizes: {
    xs: rem('12px'),
    sm: rem('14px'),
    md: rem('16px'),
    lg: rem('18px'),
    xl: rem('20px'),
    '2xl': rem('24px'),
    '3xl': rem('30px'),
    '4xl': rem('36px'),
    '5xl': rem('48px'),
  },
  lineHeights: {
    xs: rem('18px'),
    sm: rem('20px'),
    md: rem('24px'),
    lg: rem('28px'),
  },
  cursorType: 'pointer',
  other: {
    style: 'shadcn',
  },
})

export const shadcnCssVariableResolver: CSSVariablesResolver = () => ({
  variables: {
    '--mantine-heading-font-weight': '600',
    '--mantine-primary-color-filled-hover': alpha('var(--mantine-primary-color-filled)', 0.9),
    '--mantine-primary-color-light': 'var(--mantine-color-orange-light)',
    '--mantine-primary-color-light-hover': 'var(--mantine-color-orange-light-hover)',
    '--mantine-primary-color-light-color': 'var(--mantine-color-orange-light-color)',
  },
  light: {
    '--mantine-primary-color-contrast': 'var(--mantine-color-stone-0)',
    '--mantine-color-text': 'var(--mantine-color-stone-9)',
    '--mantine-color-body': 'var(--mantine-color-white)',
    '--mantine-color-error': 'var(--mantine-color-red-6)',
    '--mantine-color-placeholder': 'var(--mantine-color-stone-5)',
    '--mantine-color-anchor': 'var(--mantine-color-stone-8)',
    '--mantine-color-default': 'var(--mantine-color-stone-0)',
    '--mantine-color-default-hover': 'var(--mantine-color-stone-1)',
    '--mantine-color-default-color': 'var(--mantine-color-stone-9)',
    '--mantine-color-default-border': 'var(--mantine-color-stone-2)',
    '--mantine-color-dimmed': 'var(--mantine-color-stone-5)',
    '--mantine-color-secondary-filled': 'var(--mantine-color-white)',
    '--mantine-color-secondary-filled-hover': 'var(--mantine-color-stone-1)',
    '--mantine-color-secondary-light': 'var(--mantine-color-stone-1)',
    '--mantine-color-secondary-light-hover': alpha('var(--mantine-color-stone-1)', 0.8),
    '--mantine-color-secondary-light-color': 'var(--mantine-color-stone-8)',
    '--mantine-color-secondary-outline': 'var(--mantine-color-stone-2)',
    '--mantine-color-secondary-outline-hover': 'var(--mantine-color-stone-1)',
  },
  dark: {
    '--mantine-primary-color-contrast': 'var(--mantine-color-stone-0)',
    '--mantine-color-text': 'var(--mantine-color-stone-0)',
    '--mantine-color-body': 'var(--mantine-color-stone-9)',
    '--mantine-color-error': 'var(--mantine-color-red-4)',
    '--mantine-color-placeholder': 'var(--mantine-color-stone-4)',
    '--mantine-color-anchor': 'var(--mantine-color-stone-3)',
    '--mantine-color-default': 'var(--mantine-color-stone-9)',
    '--mantine-color-default-hover': 'var(--mantine-color-stone-7)',
    '--mantine-color-default-color': 'var(--mantine-color-stone-1)',
    '--mantine-color-default-border': 'var(--mantine-color-stone-7)',
    '--mantine-color-dimmed': 'var(--mantine-color-stone-4)',
    '--mantine-color-secondary-filled': 'var(--mantine-color-stone-8)',
    '--mantine-color-secondary-filled-hover': alpha('var(--mantine-color-stone-8)', 0.9),
    '--mantine-color-secondary-light': 'var(--mantine-color-stone-7)',
    '--mantine-color-secondary-light-hover': alpha('var(--mantine-color-stone-7)', 0.8),
    '--mantine-color-secondary-light-color': 'var(--mantine-color-stone-0)',
    '--mantine-color-secondary-outline': 'var(--mantine-color-stone-7)',
    '--mantine-color-secondary-outline-hover': 'var(--mantine-color-stone-7)',
  },
})
