// Auto-generated by scripts/generate-subjects.ts
// Generated at: 2026-06-02T18:32:47.954Z
// Excludes common words that are also subject codes (IS, UP, ME, etc.)
// These "unsafe" codes are only matched if uppercase or part of a clear course code (e.g. "IS 500")

export const VALID_SUBJECTS = new Set([
  "AAS",
  "ABE",
  "ACCY",
  "ACE",
  "ACES",
  "ADV",
  "AE",
  "AFAS",
  "AFRO",
  "AFST",
  "AGCM",
  "AGED",
  "AHS",
  "AIS",
  "ALEC",
  "ANSC",
  "ANTH",
  "ARAB",
  "ARCH",
  "ART",
  "ARTD",
  "ARTE",
  "ARTF",
  "ARTH",
  "ARTJ",
  "ARTS",
  "ASRM",
  "ASST",
  "ASTR",
  "ATMS",
  "BADM",
  "BASQ",
  "BCOG",
  "BCS",
  "BDI",
  "BIOC",
  "BIOE",
  "BIOP",
  "BSE",
  "BTW",
  "BUS",
  "CAS",
  "CB",
  "CDB",
  "CEE",
  "CGGE",
  "CHBE",
  "CHEM",
  "CHIN",
  "CHP",
  "CI",
  "CIC",
  "CLCV",
  "CLE",
  "CMN",
  "CPSC",
  "CS",
  "CSE",
  "CW",
  "CWL",
  "CZCH",
  "DANC",
  "DTX",
  "EALC",
  "ECE",
  "ECON",
  "EDPR",
  "EDUC",
  "EIL",
  "ENG",
  "ENGL",
  "ENSU",
  "ENT",
  "ENVS",
  "EPOL",
  "EPSY",
  "ERAM",
  "ES",
  "ESE",
  "ESL",
  "ETMA",
  "EURO",
  "EXP",
  "FAA",
  "FIN",
  "FLTE",
  "FR",
  "FSHN",
  "GC",
  "GEOL",
  "GER",
  "GGIS",
  "GLBL",
  "GMC",
  "GRK",
  "GRKM",
  "GSD",
  "GWS",
  "HBSE",
  "HDFS",
  "HEBR",
  "HIST",
  "HK",
  "HNDI",
  "HORT",
  "HT",
  "HUM",
  "IB",
  "IE",
  "INFO",
  "IS",
  "ITAL",
  "JAPN",
  "JOUR",
  "JS",
  "KOR",
  "LA",
  "LAS",
  "LAST",
  "LAT",
  "LAW",
  "LCTL",
  "LEAD",
  "LER",
  "LING",
  "LLS",
  "MACS",
  "MATH",
  "MBA",
  "MCB",
  "MDIA",
  "MDVL",
  "ME",
  "MICR",
  "MILS",
  "MIP",
  "MSE",
  "MUS",
  "MUSC",
  "MUSE",
  "NE",
  "NEUR",
  "NPRE",
  "NRES",
  "NS",
  "NUTR",
  "PATH",
  "PERS",
  "PHIL",
  "PHYS",
  "PLPA",
  "POL",
  "PORT",
  "PS",
  "PSM",
  "PSYC",
  "QUEC",
  "REES",
  "REL",
  "RHET",
  "RMLG",
  "RST",
  "RUSS",
  "SAME",
  "SBC",
  "SCAN",
  "SE",
  "SHS",
  "SLAV",
  "SLCL",
  "SOC",
  "SOCW",
  "SPAN",
  "SPED",
  "STAT",
  "SWAH",
  "TAM",
  "TE",
  "THEA",
  "TMGT",
  "TRST",
  "TURK",
  "UKR",
  "UP",
  "VCM",
  "VM",
  "WLOF",
  "WLTE",
  "WRIT",
  "YDSH"
]);

export const SUBJECT_NAMES: Record<string, string> = {
  "AAS": "Asian American Studies",
  "ABE": "Agricultural and Biological Engineering",
  "ACCY": "Accountancy",
  "ACE": "Agricultural and Consumer Economics",
  "ACES": "Agricultural, Consumer and Environmental Sciences",
  "ADV": "Advertising",
  "AE": "Aerospace Engineering",
  "AFAS": "Air Force Aerospace Studies",
  "AFRO": "African American Studies",
  "AFST": "African Studies",
  "AGCM": "Agricultural Communications",
  "AGED": "Agricultural Education",
  "AHS": "Applied Health Sciences Courses",
  "AIS": "American Indian Studies",
  "ALEC": "Agricultural Leadership, Education, and Communications Program",
  "ANSC": "Animal Sciences",
  "ANTH": "Anthropology",
  "ARAB": "Arabic",
  "ARCH": "Architecture",
  "ART": "Art",
  "ARTD": "Art--Design",
  "ARTE": "Art--Education",
  "ARTF": "Art--Foundation",
  "ARTH": "Art--History",
  "ARTJ": "Japanese Arts and Aesthetics",
  "ARTS": "Art--Studio",
  "ASRM": "Actuarial Science and Risk Management",
  "ASST": "Asian Studies",
  "ASTR": "Astronomy",
  "ATMS": "Atmospheric Sciences",
  "BADM": "Business Administration",
  "BASQ": "Basque",
  "BCOG": "Brain and Cognitive Science",
  "BCS": "Bosnian-Croatian-Serbian",
  "BDI": "Business Data and Innovation",
  "BIOC": "Biochemistry",
  "BIOE": "Bioengineering",
  "BIOP": "Biophysics",
  "BSE": "Biomedical Sciences and Engineering",
  "BTW": "Business and Technical Writing",
  "BUS": "Business",
  "CAS": "Center for Advanced Study",
  "CB": "Comparative Biosciences",
  "CDB": "Cell and Developmental Biology",
  "CEE": "Civil and Environmental Engineering",
  "CGGE": "Study of Global Gender Equity",
  "CHBE": "Chemical and Biomolecular Engineering",
  "CHEM": "Chemistry",
  "CHIN": "Chinese",
  "CHP": "Campus Honors Program Courses",
  "CI": "Curriculum and Instruction",
  "CIC": "Committee on Inst Cooperation",
  "CLCV": "Classical Civilization",
  "CLE": "Clinical Sciences and Engineering",
  "CMN": "Communication",
  "CPSC": "Crop Sciences",
  "CS": "Computer Science",
  "CSE": "Computational Science and Engineering",
  "CW": "Creative Writing",
  "CWL": "Comparative and World Literature",
  "CZCH": "Czech",
  "DANC": "Dance",
  "DTX": "Human-Centered Design and Design Thinking",
  "EALC": "East Asian Language and Culture",
  "ECE": "Electrical and Computer Engineering",
  "ECON": "Economics",
  "EDPR": "Educational Practice",
  "EDUC": "Education",
  "EIL": "English as an International Language",
  "ENG": "Engineering",
  "ENGL": "English",
  "ENSU": "Environmental Sustainability",
  "ENT": "Entomology",
  "ENVS": "Environmental Studies",
  "EPOL": "Education Policy, Organization and Leadership",
  "EPSY": "Educational Psychology",
  "ERAM": "Education Research & Methods",
  "ES": "Energy Systems",
  "ESE": "Earth, Society, and Environment",
  "ESL": "English as a Second Language",
  "ETMA": "Engineering Technology and Management for Agricultural Systems",
  "EURO": "European Union Studies",
  "EXP": "Exploratory Studies",
  "FAA": "Fine and Applied Arts",
  "FIN": "Finance",
  "FLTE": "Foreign Language Teacher Education",
  "FR": "French",
  "FSHN": "Food Science and Human Nutrition",
  "GC": "Graduate College",
  "GEOL": "Geology",
  "GER": "German",
  "GGIS": "Geography & Geographic Information Science",
  "GLBL": "Global Studies",
  "GMC": "Germanic",
  "GRK": "Greek",
  "GRKM": "Modern Greek",
  "GSD": "Game Studies and Design",
  "GWS": "Gender and Women's Studies",
  "HBSE": "Healthcare, Biomedical Science and Engineering",
  "HDFS": "Human Development and Family Studies",
  "HEBR": "Hebrew, Modern and Classical",
  "HIST": "History",
  "HK": "Health and Kinesiology",
  "HNDI": "Hindi",
  "HORT": "Horticulture",
  "HT": "Health Technology",
  "HUM": "Humanities Courses",
  "IB": "Integrative Biology",
  "IE": "Industrial Engineering",
  "INFO": "Informatics",
  "IS": "Information Sciences",
  "ITAL": "Italian",
  "JAPN": "Japanese",
  "JOUR": "Journalism",
  "JS": "Jewish Studies",
  "KOR": "Korean",
  "LA": "Landscape Architecture",
  "LAS": "Liberal Arts and Sciences",
  "LAST": "Latin American and Caribbean Studies",
  "LAT": "Latin",
  "LAW": "Law",
  "LCTL": "Less Commonly Taught Languages",
  "LEAD": "Organizational and Community Leadership",
  "LER": "Labor and Employment Relations",
  "LING": "Linguistics",
  "LLS": "Latina/Latino Studies",
  "MACS": "Media and Cinema Studies",
  "MATH": "Mathematics",
  "MBA": "Regular MBA Program Administration",
  "MCB": "Molecular and Cell Biology",
  "MDIA": "Media",
  "MDVL": "Medieval Studies",
  "ME": "Mechanical Engineering",
  "MICR": "Microbiology",
  "MILS": "Military Science",
  "MIP": "Molecular and Integrative Physiology",
  "MSE": "Materials Science and Engineering",
  "MUS": "Music",
  "MUSC": "Music Lessons and Ensembles",
  "MUSE": "Museum Studies",
  "NE": "Neural Engineering",
  "NEUR": "Neuroscience",
  "NPRE": "Nuclear, Plasma, and Radiological Engineering",
  "NRES": "Natural Resources and Environmental Sciences",
  "NS": "Naval Science",
  "NUTR": "Nutritional Sciences",
  "PATH": "Pathobiology",
  "PERS": "Persian",
  "PHIL": "Philosophy",
  "PHYS": "Physics",
  "PLPA": "Plant Pathology",
  "POL": "Polish",
  "PORT": "Portuguese",
  "PS": "Political Science",
  "PSM": "Professional Science Master's Program",
  "PSYC": "Psychology",
  "QUEC": "Quechua",
  "REES": "Russian, East European and Eurasian Studies",
  "REL": "Religion",
  "RHET": "Rhetoric and Composition",
  "RMLG": "Romance Linguistics",
  "RST": "Recreation, Sport, and Tourism",
  "RUSS": "Russian",
  "SAME": "South Asian and Middle Eastern Studies",
  "SBC": "Strategic Brand Communication",
  "SCAN": "Scandinavian",
  "SE": "Systems Engineering and Design",
  "SHS": "Speech and Hearing Science",
  "SLAV": "Slavic",
  "SLCL": "Literatures, Cultures, and Linguistics",
  "SOC": "Sociology",
  "SOCW": "Social Work",
  "SPAN": "Spanish",
  "SPED": "Special Education",
  "STAT": "Statistics",
  "SWAH": "Swahili",
  "TAM": "Theoretical and Applied Mechanics",
  "TE": "Technology Entrepreneurship",
  "THEA": "Theatre",
  "TMGT": "Technology and Management Courses",
  "TRST": "Translation Studies",
  "TURK": "Turkish",
  "UKR": "Ukrainian",
  "UP": "Urban and Regional Planning",
  "VCM": "Veterinary Clinical Medicine",
  "VM": "Veterinary Medicine Courses",
  "WLOF": "Wolof",
  "WLTE": "World Language Teacher Education",
  "WRIT": "Writing Studies",
  "YDSH": "Yiddish"
};

export const SUBJECT_ALIASES: Array<{ subject: string; aliases: string[] }> = [
  {
    "subject": "AAS",
    "aliases": [
      "aas",
      "asian american studies"
    ]
  },
  {
    "subject": "ABE",
    "aliases": [
      "abe",
      "agricultural and biological engineering",
      "agricultural biological engineering"
    ]
  },
  {
    "subject": "ACCY",
    "aliases": [
      "accountancy",
      "accy"
    ]
  },
  {
    "subject": "ACE",
    "aliases": [
      "ace",
      "agricultural and consumer economics",
      "agricultural consumer economics"
    ]
  },
  {
    "subject": "ACES",
    "aliases": [
      "aces",
      "agricultural consumer and environmental sciences",
      "agricultural consumer environmental sciences"
    ]
  },
  {
    "subject": "ADV",
    "aliases": [
      "adv",
      "advertising"
    ]
  },
  {
    "subject": "AE",
    "aliases": [
      "ae",
      "aerospace engineering"
    ]
  },
  {
    "subject": "AFAS",
    "aliases": [
      "afas",
      "air force aerospace studies"
    ]
  },
  {
    "subject": "AFRO",
    "aliases": [
      "african american studies",
      "afro"
    ]
  },
  {
    "subject": "AFST",
    "aliases": [
      "african studies",
      "afst"
    ]
  },
  {
    "subject": "AGCM",
    "aliases": [
      "agcm",
      "agricultural communications"
    ]
  },
  {
    "subject": "AGED",
    "aliases": [
      "aged",
      "agricultural education"
    ]
  },
  {
    "subject": "AHS",
    "aliases": [
      "ahs",
      "applied health sciences",
      "applied health sciences courses"
    ]
  },
  {
    "subject": "AIS",
    "aliases": [
      "ais",
      "american indian studies"
    ]
  },
  {
    "subject": "ALEC",
    "aliases": [
      "agricultural leadership education and communications program",
      "agricultural leadership education communications program",
      "alec"
    ]
  },
  {
    "subject": "ANSC",
    "aliases": [
      "animal sciences",
      "ansc"
    ]
  },
  {
    "subject": "ANTH",
    "aliases": [
      "anth",
      "anthro",
      "anthropology"
    ]
  },
  {
    "subject": "ARAB",
    "aliases": [
      "arab",
      "arabic"
    ]
  },
  {
    "subject": "ARCH",
    "aliases": [
      "arch",
      "architecture"
    ]
  },
  {
    "subject": "ART",
    "aliases": []
  },
  {
    "subject": "ARTD",
    "aliases": [
      "art design",
      "artd"
    ]
  },
  {
    "subject": "ARTE",
    "aliases": [
      "art education",
      "arte"
    ]
  },
  {
    "subject": "ARTF",
    "aliases": [
      "art foundation",
      "artf"
    ]
  },
  {
    "subject": "ARTH",
    "aliases": [
      "art history",
      "arth"
    ]
  },
  {
    "subject": "ARTJ",
    "aliases": [
      "artj",
      "japanese arts aesthetics",
      "japanese arts and aesthetics"
    ]
  },
  {
    "subject": "ARTS",
    "aliases": [
      "art studio",
      "arts"
    ]
  },
  {
    "subject": "ASRM",
    "aliases": [
      "actuarial science and risk management",
      "actuarial science risk management",
      "asrm"
    ]
  },
  {
    "subject": "ASST",
    "aliases": [
      "asian studies",
      "asst"
    ]
  },
  {
    "subject": "ASTR",
    "aliases": [
      "astr",
      "astronomy"
    ]
  },
  {
    "subject": "ATMS",
    "aliases": [
      "atmospheric sciences",
      "atms"
    ]
  },
  {
    "subject": "BADM",
    "aliases": [
      "badm",
      "business administration"
    ]
  },
  {
    "subject": "BASQ",
    "aliases": [
      "basq",
      "basque"
    ]
  },
  {
    "subject": "BCOG",
    "aliases": [
      "bcog",
      "brain and cognitive science",
      "brain cognitive science"
    ]
  },
  {
    "subject": "BCS",
    "aliases": [
      "bcs",
      "bosnian croatian serbian"
    ]
  },
  {
    "subject": "BDI",
    "aliases": [
      "bdi",
      "business data and innovation",
      "business data innovation"
    ]
  },
  {
    "subject": "BIOC",
    "aliases": [
      "bioc",
      "biochemistry"
    ]
  },
  {
    "subject": "BIOE",
    "aliases": [
      "bioe",
      "bioengineering"
    ]
  },
  {
    "subject": "BIOP",
    "aliases": [
      "biop",
      "biophysics"
    ]
  },
  {
    "subject": "BSE",
    "aliases": [
      "biomedical sciences and engineering",
      "biomedical sciences engineering",
      "bse"
    ]
  },
  {
    "subject": "BTW",
    "aliases": [
      "btw",
      "business and technical writing",
      "business technical writing"
    ]
  },
  {
    "subject": "BUS",
    "aliases": []
  },
  {
    "subject": "CAS",
    "aliases": [
      "cas",
      "center for advanced study"
    ]
  },
  {
    "subject": "CB",
    "aliases": [
      "cb",
      "comparative biosciences"
    ]
  },
  {
    "subject": "CDB",
    "aliases": [
      "cdb",
      "cell and developmental biology",
      "cell developmental biology"
    ]
  },
  {
    "subject": "CEE",
    "aliases": [
      "cee",
      "civil and environmental engineering",
      "civil environmental engineering"
    ]
  },
  {
    "subject": "CGGE",
    "aliases": [
      "cgge",
      "study of global gender equity"
    ]
  },
  {
    "subject": "CHBE",
    "aliases": [
      "chbe",
      "chemical and biomolecular engineering",
      "chemical biomolecular engineering"
    ]
  },
  {
    "subject": "CHEM",
    "aliases": [
      "chem",
      "chemistry"
    ]
  },
  {
    "subject": "CHIN",
    "aliases": [
      "chin",
      "chinese"
    ]
  },
  {
    "subject": "CHP",
    "aliases": [
      "campus honors program",
      "campus honors program courses",
      "chp"
    ]
  },
  {
    "subject": "CI",
    "aliases": [
      "ci",
      "curriculum and instruction",
      "curriculum instruction"
    ]
  },
  {
    "subject": "CIC",
    "aliases": [
      "cic",
      "committee on inst cooperation"
    ]
  },
  {
    "subject": "CLCV",
    "aliases": [
      "classical civilization",
      "clcv"
    ]
  },
  {
    "subject": "CLE",
    "aliases": [
      "cle",
      "clinical sciences and engineering",
      "clinical sciences engineering"
    ]
  },
  {
    "subject": "CMN",
    "aliases": [
      "cmn",
      "communication"
    ]
  },
  {
    "subject": "CPSC",
    "aliases": [
      "cpsc",
      "crop sciences"
    ]
  },
  {
    "subject": "CS",
    "aliases": [
      "comp sci",
      "computer science",
      "cs"
    ]
  },
  {
    "subject": "CSE",
    "aliases": [
      "computational science and engineering",
      "computational science engineering",
      "cse"
    ]
  },
  {
    "subject": "CW",
    "aliases": [
      "creative writing",
      "cw"
    ]
  },
  {
    "subject": "CWL",
    "aliases": [
      "comparative and world literature",
      "comparative world literature",
      "cwl"
    ]
  },
  {
    "subject": "CZCH",
    "aliases": [
      "czch",
      "czech"
    ]
  },
  {
    "subject": "DANC",
    "aliases": [
      "danc",
      "dance"
    ]
  },
  {
    "subject": "DTX",
    "aliases": [
      "dtx",
      "human centered design and design thinking",
      "human centered design design thinking"
    ]
  },
  {
    "subject": "EALC",
    "aliases": [
      "ealc",
      "east asian language and culture",
      "east asian language culture"
    ]
  },
  {
    "subject": "ECE",
    "aliases": [
      "ece",
      "elec comp eng",
      "electrical and computer engineering",
      "electrical computer engineering"
    ]
  },
  {
    "subject": "ECON",
    "aliases": [
      "econ",
      "economics"
    ]
  },
  {
    "subject": "EDPR",
    "aliases": [
      "edpr",
      "educational practice"
    ]
  },
  {
    "subject": "EDUC",
    "aliases": [
      "educ",
      "education"
    ]
  },
  {
    "subject": "EIL",
    "aliases": [
      "eil",
      "english as an international language"
    ]
  },
  {
    "subject": "ENG",
    "aliases": []
  },
  {
    "subject": "ENGL",
    "aliases": [
      "engl",
      "english"
    ]
  },
  {
    "subject": "ENSU",
    "aliases": [
      "ensu",
      "environmental sustainability"
    ]
  },
  {
    "subject": "ENT",
    "aliases": [
      "ent",
      "entomology"
    ]
  },
  {
    "subject": "ENVS",
    "aliases": [
      "environmental studies",
      "envs"
    ]
  },
  {
    "subject": "EPOL",
    "aliases": [
      "education policy organization and leadership",
      "education policy organization leadership",
      "epol"
    ]
  },
  {
    "subject": "EPSY",
    "aliases": [
      "educational psychology",
      "epsy"
    ]
  },
  {
    "subject": "ERAM",
    "aliases": [
      "education research and methods",
      "education research methods",
      "eram"
    ]
  },
  {
    "subject": "ES",
    "aliases": [
      "energy systems",
      "es"
    ]
  },
  {
    "subject": "ESE",
    "aliases": [
      "earth society and environment",
      "earth society environment",
      "ese"
    ]
  },
  {
    "subject": "ESL",
    "aliases": [
      "english as a second language",
      "esl"
    ]
  },
  {
    "subject": "ETMA",
    "aliases": [
      "engineering technology and management for agricultural systems",
      "engineering technology management for agricultural systems",
      "etma"
    ]
  },
  {
    "subject": "EURO",
    "aliases": [
      "euro",
      "european union studies"
    ]
  },
  {
    "subject": "EXP",
    "aliases": [
      "exp",
      "exploratory studies"
    ]
  },
  {
    "subject": "FAA",
    "aliases": [
      "faa",
      "fine and applied arts",
      "fine applied arts"
    ]
  },
  {
    "subject": "FIN",
    "aliases": [
      "fin",
      "finance"
    ]
  },
  {
    "subject": "FLTE",
    "aliases": [
      "flte",
      "foreign language teacher education"
    ]
  },
  {
    "subject": "FR",
    "aliases": [
      "fr",
      "french"
    ]
  },
  {
    "subject": "FSHN",
    "aliases": [
      "food science and human nutrition",
      "food science human nutrition",
      "fshn"
    ]
  },
  {
    "subject": "GC",
    "aliases": [
      "gc",
      "graduate college"
    ]
  },
  {
    "subject": "GEOL",
    "aliases": [
      "geol",
      "geology"
    ]
  },
  {
    "subject": "GER",
    "aliases": [
      "ger",
      "german"
    ]
  },
  {
    "subject": "GGIS",
    "aliases": [
      "geography and geographic information science",
      "geography geographic information science",
      "ggis"
    ]
  },
  {
    "subject": "GLBL",
    "aliases": [
      "glbl",
      "global studies"
    ]
  },
  {
    "subject": "GMC",
    "aliases": [
      "germanic",
      "gmc"
    ]
  },
  {
    "subject": "GRK",
    "aliases": [
      "greek",
      "grk"
    ]
  },
  {
    "subject": "GRKM",
    "aliases": [
      "grkm",
      "modern greek"
    ]
  },
  {
    "subject": "GSD",
    "aliases": [
      "game studies and design",
      "game studies design",
      "gsd"
    ]
  },
  {
    "subject": "GWS",
    "aliases": [
      "gender and women's studies",
      "gender women's studies",
      "gws"
    ]
  },
  {
    "subject": "HBSE",
    "aliases": [
      "hbse",
      "healthcare biomedical science and engineering",
      "healthcare biomedical science engineering"
    ]
  },
  {
    "subject": "HDFS",
    "aliases": [
      "hdfs",
      "human development and family studies",
      "human development family studies"
    ]
  },
  {
    "subject": "HEBR",
    "aliases": [
      "hebr",
      "hebrew modern and classical",
      "hebrew modern classical"
    ]
  },
  {
    "subject": "HIST",
    "aliases": [
      "hist",
      "history"
    ]
  },
  {
    "subject": "HK",
    "aliases": [
      "health and kinesiology",
      "health kinesiology",
      "hk"
    ]
  },
  {
    "subject": "HNDI",
    "aliases": [
      "hindi",
      "hndi"
    ]
  },
  {
    "subject": "HORT",
    "aliases": [
      "hort",
      "horticulture"
    ]
  },
  {
    "subject": "HT",
    "aliases": [
      "health technology",
      "ht"
    ]
  },
  {
    "subject": "HUM",
    "aliases": [
      "humanities courses"
    ]
  },
  {
    "subject": "IB",
    "aliases": [
      "ib",
      "integrative biology"
    ]
  },
  {
    "subject": "IE",
    "aliases": [
      "ie",
      "industrial engineering"
    ]
  },
  {
    "subject": "INFO",
    "aliases": [
      "info",
      "informatics"
    ]
  },
  {
    "subject": "IS",
    "aliases": [
      "information sciences"
    ]
  },
  {
    "subject": "ITAL",
    "aliases": [
      "ital",
      "italian"
    ]
  },
  {
    "subject": "JAPN",
    "aliases": [
      "japanese",
      "japn"
    ]
  },
  {
    "subject": "JOUR",
    "aliases": [
      "jour",
      "journalism"
    ]
  },
  {
    "subject": "JS",
    "aliases": [
      "jewish studies",
      "js"
    ]
  },
  {
    "subject": "KOR",
    "aliases": [
      "kor",
      "korean"
    ]
  },
  {
    "subject": "LA",
    "aliases": [
      "la",
      "landscape architecture"
    ]
  },
  {
    "subject": "LAS",
    "aliases": [
      "las",
      "liberal arts and sciences",
      "liberal arts sciences"
    ]
  },
  {
    "subject": "LAST",
    "aliases": [
      "last",
      "latin american and caribbean studies",
      "latin american caribbean studies"
    ]
  },
  {
    "subject": "LAT",
    "aliases": [
      "lat",
      "latin"
    ]
  },
  {
    "subject": "LAW",
    "aliases": []
  },
  {
    "subject": "LCTL",
    "aliases": [
      "lctl",
      "less commonly taught languages"
    ]
  },
  {
    "subject": "LEAD",
    "aliases": [
      "lead",
      "organizational and community leadership",
      "organizational community leadership"
    ]
  },
  {
    "subject": "LER",
    "aliases": [
      "labor and employment relations",
      "labor employment relations",
      "ler"
    ]
  },
  {
    "subject": "LING",
    "aliases": [
      "ling",
      "linguistics"
    ]
  },
  {
    "subject": "LLS",
    "aliases": [
      "latina latino studies",
      "lls"
    ]
  },
  {
    "subject": "MACS",
    "aliases": [
      "macs",
      "media and cinema studies",
      "media cinema studies"
    ]
  },
  {
    "subject": "MATH",
    "aliases": [
      "math",
      "mathematics"
    ]
  },
  {
    "subject": "MBA",
    "aliases": [
      "mba",
      "regular mba program administration"
    ]
  },
  {
    "subject": "MCB",
    "aliases": [
      "mcb",
      "molecular and cell biology",
      "molecular cell bio",
      "molecular cell biology",
      "molecular cellular biology"
    ]
  },
  {
    "subject": "MDIA",
    "aliases": [
      "mdia",
      "media"
    ]
  },
  {
    "subject": "MDVL",
    "aliases": [
      "mdvl",
      "medieval studies"
    ]
  },
  {
    "subject": "ME",
    "aliases": [
      "mechanical engineering"
    ]
  },
  {
    "subject": "MICR",
    "aliases": [
      "micr",
      "microbiology"
    ]
  },
  {
    "subject": "MILS",
    "aliases": [
      "military science",
      "mils"
    ]
  },
  {
    "subject": "MIP",
    "aliases": [
      "mip",
      "molecular and integrative physiology",
      "molecular integrative physiology"
    ]
  },
  {
    "subject": "MSE",
    "aliases": [
      "materials science and engineering",
      "materials science engineering",
      "mse"
    ]
  },
  {
    "subject": "MUS",
    "aliases": [
      "mus",
      "music"
    ]
  },
  {
    "subject": "MUSC",
    "aliases": [
      "musc",
      "music lessons and ensembles",
      "music lessons ensembles"
    ]
  },
  {
    "subject": "MUSE",
    "aliases": [
      "muse",
      "museum studies"
    ]
  },
  {
    "subject": "NE",
    "aliases": [
      "ne",
      "neural engineering"
    ]
  },
  {
    "subject": "NEUR",
    "aliases": [
      "neur",
      "neuroscience"
    ]
  },
  {
    "subject": "NPRE",
    "aliases": [
      "npre",
      "nuclear plasma and radiological engineering",
      "nuclear plasma radiological engineering"
    ]
  },
  {
    "subject": "NRES",
    "aliases": [
      "natural resources and environmental sciences",
      "natural resources environmental sciences",
      "nres"
    ]
  },
  {
    "subject": "NS",
    "aliases": [
      "naval science",
      "ns"
    ]
  },
  {
    "subject": "NUTR",
    "aliases": [
      "nutr",
      "nutritional sciences"
    ]
  },
  {
    "subject": "PATH",
    "aliases": [
      "path",
      "pathobiology"
    ]
  },
  {
    "subject": "PERS",
    "aliases": [
      "pers",
      "persian"
    ]
  },
  {
    "subject": "PHIL",
    "aliases": [
      "phil",
      "philosophy"
    ]
  },
  {
    "subject": "PHYS",
    "aliases": [
      "phys",
      "physics"
    ]
  },
  {
    "subject": "PLPA",
    "aliases": [
      "plant pathology",
      "plpa"
    ]
  },
  {
    "subject": "POL",
    "aliases": [
      "pol",
      "polish"
    ]
  },
  {
    "subject": "PORT",
    "aliases": [
      "port",
      "portuguese"
    ]
  },
  {
    "subject": "PS",
    "aliases": [
      "poli sci",
      "political sci",
      "political science",
      "poly sci",
      "ps"
    ]
  },
  {
    "subject": "PSM",
    "aliases": [
      "professional science master's program",
      "psm"
    ]
  },
  {
    "subject": "PSYC",
    "aliases": [
      "psyc",
      "psych",
      "psychology"
    ]
  },
  {
    "subject": "QUEC",
    "aliases": [
      "quec",
      "quechua"
    ]
  },
  {
    "subject": "REES",
    "aliases": [
      "rees",
      "russian east european and eurasian studies",
      "russian east european eurasian studies"
    ]
  },
  {
    "subject": "REL",
    "aliases": [
      "rel",
      "religion"
    ]
  },
  {
    "subject": "RHET",
    "aliases": [
      "rhet",
      "rhetoric and composition",
      "rhetoric composition"
    ]
  },
  {
    "subject": "RMLG",
    "aliases": [
      "rmlg",
      "romance linguistics"
    ]
  },
  {
    "subject": "RST",
    "aliases": [
      "recreation sport and tourism",
      "recreation sport tourism",
      "rst"
    ]
  },
  {
    "subject": "RUSS",
    "aliases": [
      "russ",
      "russian"
    ]
  },
  {
    "subject": "SAME",
    "aliases": [
      "south asian and middle eastern studies",
      "south asian middle eastern studies"
    ]
  },
  {
    "subject": "SBC",
    "aliases": [
      "sbc",
      "strategic brand communication"
    ]
  },
  {
    "subject": "SCAN",
    "aliases": [
      "scan",
      "scandinavian"
    ]
  },
  {
    "subject": "SE",
    "aliases": [
      "systems engineering and design",
      "systems engineering design"
    ]
  },
  {
    "subject": "SHS",
    "aliases": [
      "shs",
      "speech and hearing science",
      "speech hearing science"
    ]
  },
  {
    "subject": "SLAV",
    "aliases": [
      "slav",
      "slavic"
    ]
  },
  {
    "subject": "SLCL",
    "aliases": [
      "literatures cultures and linguistics",
      "literatures cultures linguistics",
      "slcl"
    ]
  },
  {
    "subject": "SOC",
    "aliases": [
      "soc",
      "sociology"
    ]
  },
  {
    "subject": "SOCW",
    "aliases": [
      "social work",
      "socw"
    ]
  },
  {
    "subject": "SPAN",
    "aliases": [
      "span",
      "spanish"
    ]
  },
  {
    "subject": "SPED",
    "aliases": [
      "special education",
      "sped"
    ]
  },
  {
    "subject": "STAT",
    "aliases": [
      "stat",
      "statistics",
      "stats"
    ]
  },
  {
    "subject": "SWAH",
    "aliases": [
      "swah",
      "swahili"
    ]
  },
  {
    "subject": "TAM",
    "aliases": [
      "tam",
      "theoretical and applied mechanics",
      "theoretical applied mechanics"
    ]
  },
  {
    "subject": "TE",
    "aliases": [
      "te",
      "technology entrepreneurship"
    ]
  },
  {
    "subject": "THEA",
    "aliases": [
      "thea",
      "theatre"
    ]
  },
  {
    "subject": "TMGT",
    "aliases": [
      "technology and management",
      "technology and management courses",
      "technology management courses",
      "tmgt"
    ]
  },
  {
    "subject": "TRST",
    "aliases": [
      "translation studies",
      "trst"
    ]
  },
  {
    "subject": "TURK",
    "aliases": [
      "turk",
      "turkish"
    ]
  },
  {
    "subject": "UKR",
    "aliases": [
      "ukr",
      "ukrainian"
    ]
  },
  {
    "subject": "UP",
    "aliases": [
      "urban and regional planning",
      "urban regional planning"
    ]
  },
  {
    "subject": "VCM",
    "aliases": [
      "vcm",
      "veterinary clinical medicine"
    ]
  },
  {
    "subject": "VM",
    "aliases": [
      "veterinary medicine",
      "veterinary medicine courses",
      "vm"
    ]
  },
  {
    "subject": "WLOF",
    "aliases": [
      "wlof",
      "wolof"
    ]
  },
  {
    "subject": "WLTE",
    "aliases": [
      "wlte",
      "world language teacher education"
    ]
  },
  {
    "subject": "WRIT",
    "aliases": [
      "writ",
      "writing studies"
    ]
  },
  {
    "subject": "YDSH",
    "aliases": [
      "ydsh",
      "yiddish"
    ]
  }
];

// Subjects that are also common English words - unsafe for lowercase matching
export const UNSAFE_LOWERCASE_SUBJECTS = new Set([
  "A",
  "AM",
  "AN",
  "ART",
  "AS",
  "AT",
  "BE",
  "BUS",
  "BY",
  "DO",
  "ENG",
  "GO",
  "HE",
  "HI",
  "HIS",
  "HUM",
  "I",
  "ID",
  "IF",
  "IN",
  "IS",
  "IT",
  "LAW",
  "ME",
  "MY",
  "NO",
  "OF",
  "OH",
  "OK",
  "ON",
  "ONE",
  "OR",
  "SAME",
  "SE",
  "SIX",
  "SO",
  "TEN",
  "THE",
  "TO",
  "TWO",
  "UP",
  "US",
  "WE"
]);

// Subjects that MUST be allowed in lowercase because they are extremely common search terms
// and unlikely to be used as normal words in a course search context (or the ambiguity is acceptable)
export const SAFE_LOWERCASE_SUBJECTS = new Set([
  "adv",
  "anth",
  "arch",
  "astr",
  "badm",
  "bio",
  "chbe",
  "chem",
  "cs",
  "dance",
  "ece",
  "econ",
  "engl",
  "fin",
  "geol",
  "hist",
  "jour",
  "ling",
  "math",
  "mus",
  "nres",
  "phil",
  "phys",
  "pol",
  "psyc",
  "soc",
  "stat",
  "thea"
]);
