name = "uiuc-course-search"
main = "src/index.ts"
compatibility_date = "2026-08-30"
compatibility_flags = ["nodejs_compat"]

[vars]
# API endpoints
CISAPI_BASE = "https://courses.illinois.edu/cisapp/explorer"
FEEDBACK_ALLOWED_ORIGINS = "https://uiuc-course-search-web.pages.dev"

# Sync settings
SYNC_CONCURRENCY = "25"

[triggers]
crons = [
  "0 10,22 * * *",
  "*/15 * * * *",
  "0 8 * * SUN",
  "*/5 * * * *"
]

[[d1_databases]]
binding = "DB"
database_name = "uiuc-course-search-db-production"
database_id = "ed2229a8-232e-4d5d-b00a-d0a68d3ef2e8"

[[kv_namespaces]]
binding = "GPA_CACHE"
id = "d7e1138ab1344bd2b102ed3502eb0b9f"
preview_id = "d6493db5a2db45ca8568c9d220a8e2b6"

[[ratelimits]]
name = "SEARCH_RATE_LIMITER"
namespace_id = "26060101"

  [ratelimits.simple]
  limit = 120
  period = 60

[[ratelimits]]
name = "COURSE_RATE_LIMITER"
namespace_id = "26060102"

  [ratelimits.simple]
  limit = 240
  period = 60

[[ratelimits]]
name = "FEEDBACK_RATE_LIMITER"
namespace_id = "26060103"

  [ratelimits.simple]
  limit = 20
  period = 60

[env.staging]
name = "uiuc-course-search-staging"
workers_dev = true
preview_urls = false

[env.staging.triggers]
crons = []

[env.staging.vars]
CISAPI_BASE = "https://courses.illinois.edu/cisapp/explorer"
FEEDBACK_ALLOWED_ORIGINS = "https://staging.uiuc-course-search-web.pages.dev"
SYNC_CONCURRENCY = "25"
[[env.staging.d1_databases]]
binding = "DB"
database_name = "uiuc-course-search-db-staging"
database_id = "418173df-c007-48ff-8560-4d7347439e6a"

[[env.staging.kv_namespaces]]
binding = "GPA_CACHE"
id = "ad02afba85fb40aa9c7d2abceb15d896"

[[env.staging.ratelimits]]
name = "SEARCH_RATE_LIMITER"
namespace_id = "26060111"

  [env.staging.ratelimits.simple]
  limit = 120
  period = 60

[[env.staging.ratelimits]]
name = "COURSE_RATE_LIMITER"
namespace_id = "26060112"

  [env.staging.ratelimits.simple]
  limit = 240
  period = 60

[[env.staging.ratelimits]]
name = "FEEDBACK_RATE_LIMITER"
namespace_id = "26060113"

  [env.staging.ratelimits.simple]
  limit = 20
  period = 60
